---
# See if NFD has been successfully installed
- name: Check if Node Feature Discovery has already been installed
  block:
    - name: CRD check - Ci mode 
      shell: > 
        oc get crds | grep nodefeaturediscoveries.nfd.openshift.io
      register: nfd_ci_crd_check
      until:
      - nfd_ci_crd_check.rc == 0
      retries: 10
      delay: 10
    - name: Pods status 
      shell: |
        POD_STATE=$(oc get po -n openshift-nfd -o custom-columns=CONTAINER:.status.phase --no-headers)
        for i in $POD_STATE
        do
          if [[ $i != "Running" ]]
          then 
                  exit 1
          fi
          echo $i
        done
      register: nfd_ci_pod_health_check
      until:
      - nfd_ci_pod_health_check.rc == 0
      retries: 10
      delay: 10
