---
# Install NFD to the cluster
- name: Deploy the operator
  make:
    chdir: '{{ nfd_download_path }}'
    target: 'deploy'
    params:
      PULLPOLICY: "Always"
      ORG: "openshift-psap"


# Let user know the success
- debug:
    msg: 'NFD successfully installed to your cluster.'
