---
# See if NFD has been installed to the user's cluster
- name: Check if Node Feature Discovery has already been installed
  block:
    - name: Checking if Node Feature Discovery has already been installed to your cluster
      shell: 'oc get crds | grep nodefeaturediscoveries.nfd.openshift.io'
      register: nfd_installation
  rescue:
    - name: Node Feature Discovery not installed to your cluster.
      debug:
        msg: >
          Node Feature Discovery (NFD) has not been installed to your cluster. Could not
          find NFD custom resources. Ignoring false error. Continuing...

# If the user is attempting to uninstall NFD when NFD is *not* installed
- block:

  # Error if un uninstall user mode
  - name: Cannot uninstall NFD
    fail:
      msg: >
        Node Feature Discovery (NFD) is not installed; therefore, it is not possible to
        uninstall it. Ending the play now.
    when: user_mode == 'uninstall'
  # Skip if under Ci mode
  - name: Ci mode check
    debug:
      msg: >
        Node feature discovery (NFD) was not installed, Ci only check
    when: user_mode == 'ci'

  when: nfd_installation.stdout == '' and (user_mode == 'uninstall' or user_mode == 'ci')

# Let user know if NFD has been installed to the cluster if the user wants to install it,
# but does not force a reinstall.
- debug:
    msg: >
      Node Feature Discovery (NFD) is already installed to your cluster. If you want to
      force a reinstall, set the 'force_reinstall' extra var equal to 'yes' when running
      the main playbook.
  when: nfd_installation.stdout != '' and force_reinstall == 'no'

# If forcing a reinstall or doing a fresh install, then call the following block
- block:

  # Download the git repo
  - include_tasks: roles/openshift_nfd/tasks/clone_nfd_git_repo.yml

  # Call the below playbook when the user is forcing a reinstall of NFD
  - include_tasks: uninstall_nfd.yml
    when: >
      (nfd_installation.stdout != '' and force_reinstall == 'yes') or
      (nfd_installation.stdout != '' and user_mode == 'uninstall') or
      (nfd_installation.stdout != '' and user_mode == 'ci')

  # Deploy the operator
  - include_tasks: roles/openshift_nfd/tasks/deploy_operator.yml
    when: >
      user_mode == 'install' or user_mode == 'ci'

  # Remove the NFD download folder
  - name: Remove NFD git repo
    file:
      state: absent
      path: '{{ nfd_download_path }}'

  when: >
    (nfd_installation.stdout == '' and user_mode == 'install') or
    (nfd_installation.stdout == '' and user_mode == 'ci') or
    (nfd_installation.stdout != '' and user_mode == 'install' and force_reinstall == 'yes') or
    (nfd_installation.stdout != '' and user_mode == 'uninstall')

# Ci block
- block:

  - include_tasks: ci_checks.yml

  when: user_mode == 'ci'
