---
# This task file is run with import_role for localhost from gpu-burst.yml

- name: Create OpenShift object
  command: >
    bash -c "oc create -f '{{ gpu_machineset_deff }}' --kubeconfig '{{ kubeconfig }}'"
  register: oc_create_gpu

- name: Check machine is provisioned
  command: >
    bash -c "oc get machines --kubeconfig '{{ kubeconfig }}' -n openshift-machine-api |grep '{{ gpu_instance_type }}' |awk '{ print $2 }'"
  register: gpu_machine_state
  until:
  - gpu_machine_state.stdout == 'Running'
  retries: 45
  delay: 10
