---
# This task file is run with import_role for localhost from gpu-burst.yml

- name: Get cluster worker nodes
  command: >
    oc get nodes
    --kubeconfig={{ kubeconfig }}
    --output=name --selector='node-role.kubernetes.io/worker'
  register: oc_get_workers
  until:
  - oc_get_workers.stdout != ''
  retries: 30
  delay: 5

- name: Get worker machineset name
  command: >
    bash -c "oc get machinesets -n openshift-machine-api --kubeconfig={{ kubeconfig }} |grep worker |awk '{ print $1 }'"
  register: oc_get_machinesets
  until: 
  - oc_get_machinesets.stdout != ''
  retries: 30
  delay: 5

- name: Get worker machineset template
  shell: >
    oc get machineset {{ oc_get_machinesets.stdout_lines[0] }} --kubeconfig {{ kubeconfig }} -n openshift-machine-api -o json |jq -c 
  register: worker_machine_set
  until:
  - worker_machine_set != ''
  retries: 30
  delay: 5

- name: Save machineset json template    
  copy: 
    content: "{{ worker_machine_set.stdout }}" 
    dest:  "{{ ansible_env.PWD }}/{{ gpu_machineset_template }}"
  delegate_to: localhost    

- name: Generate GPU machine set file
  shell: >
    {{ parse_machine_set | quote}} {{ gpu_machineset_template }} {{ gpu_instance_type }} 
  register: gpu_machine_set_file
  until:
  - gpu_machine_set_file != ''
  retries: 30
  delay: 5

- name: Save machineset definition file    
  copy: 
    content: "{{ gpu_machine_set_file.stdout }}" 
    dest:  "{{ ansible_env.PWD }}/{{ gpu_machineset_deff }}"
  delegate_to: localhost    
