---
# Install SRO to the cluster
- name: Deploy the operator
  make:
    chdir: '{{ sro_download_path }}'
    target: 'deploy'
    params:
      PULLPOLICY: "Always"

# Let user know the success
- debug:
    msg: 'SRO successfully installed to your cluster.'
