---
# Install golang on RHEL 7 so we can build SRO
- name: Installing golang
  yum:
    name: golang
    state: latest
  when: rhel_ver == '7'
  become: yes

# If using RHEL 8, then install golang with dnf
- name: Installing golang 
  dnf:
    name: golang
    state: latest
  when: rhel_ver == '8'
  become: yes
