---
# Manifest for installing NV GPU operator from operator Hub
gpu_operator_namespace: roles/nv_gpu/files/001_namespace.yaml
gpu_operator_operatorgroup: roles/nv_gpu/files/002_operatorgroup.yaml
gpu_operator_operatorhub_sub: roles/nv_gpu/files/003_operator_sub.yaml
gpu_operator_crs: roles/nv_gpu/files/004_customresources.yaml
