---
# Install and test GPU Operator
- name: CI Run NVidia GPU operator
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    kubeconfig: "{{ ansible_env.KUBECONFIG }}"
  roles:
    - role: nv_gpu
    
